'use client';
import { useState } from 'react';
import PageHero from '@/components/PageHero';
import { site } from '@/lib/site';

export default function Page(){
 const [sent,setSent]=useState(false);
 function submit(e){e.preventDefault();const fd=new FormData(e.currentTarget);const body=[`Naam ouder/speler: ${fd.get('naam')}`,`Leeftijd: ${fd.get('leeftijd')}`,`Club/niveau: ${fd.get('club')}`,`Telefoon: ${fd.get('telefoon')}`,`Interesse: ${fd.get('interesse')}`,`Bericht: ${fd.get('bericht')}`].join('\n');window.location.href=`mailto:${site.email}?subject=${encodeURIComponent('FOOTWORK aanvraag')}&body=${encodeURIComponent(body)}`;setSent(true)}
 return <><PageHero eyebrow="CONTACT • ’T GOOI" title="LEVEL UP" highlight="YOUR GAME." text="Vraag een proeftraining, Performance Test, FOOTWORK 8 of clubprogramma aan. We nemen daarna contact op om het juiste niveau en moment te bespreken." image="/images/football-training.jpg"/><section className="section contact-layout"><div><span className="eyebrow">AANMELDEN</span><h2>VERTEL ONS KORT WIE JE BENT.</h2><p>Gebruik het formulier voor een speler of clubaanvraag. Het formulier opent op dit moment jullie e-mailprogramma met de gegevens ingevuld.</p><div className="contact-cards"><article><strong>Locatie</strong><span>{site.location}</span></article><article><strong>E-mail</strong><span>{site.email}</span></article><article><strong>Veiligheid</strong><span>Geen hard sparren / geen hoofdcontact</span></article></div></div><form className="contact-form" onSubmit={submit}><input name="naam" placeholder="Naam ouder / speler *" required/><div className="form-row"><input name="leeftijd" placeholder="Leeftijd speler"/><input name="telefoon" placeholder="Telefoonnummer *" required/></div><input name="club" placeholder="Huidige club / niveau"/><select name="interesse" defaultValue="Proeftraining"><option>Proeftraining</option><option>Performance Test</option><option>FOOTWORK 8</option><option>1× per week</option><option>2× per week</option><option>Elite small group</option><option>Personal performance</option><option>Clubprogramma</option></select><textarea name="bericht" placeholder="Waar wil de speler vooral beter in worden?"></textarea><button className="btn btn-orange" type="submit">Aanvraag voorbereiden →</button>{sent&&<small className="form-note">Je e-mailprogramma is geopend. Controleer de aanvraag en druk daar op verzenden.</small>}</form></section></>;
}
