import Image from 'next/image';
import Link from 'next/link';

const pillars = [
  ['⚡', 'Sterker', 'Kracht, stabiliteit en duelkracht'],
  ['➤', 'Sneller', 'Acceleratie, agility en reactie'],
  ['✦', 'Explosiever', 'Power, sprongkracht en eerste meters'],
  ['⬡', 'Weerbaarder', 'Focus, discipline en zelfvertrouwen']
];
const programs = [
  { image: '/images/football-training.jpg', title: 'Voetbaltraining', text: 'Voetwerk, techniek, wendbaarheid en toepassing onder druk.', href: '/voetbaltraining' },
  { image: '/images/kickboxing-training.jpg', title: 'Kickboxing performance', text: 'Reactie, balans, ritme, discipline en weerbaarheid. Zonder hard sparren of hoofdcontact.', href: '/kickboksen' },
  { image: '/images/strength-training.jpg', title: 'Physical performance', text: 'Kracht, sprint, explosiviteit, core, landingstechniek en atletisch bewegen.', href: '/performance' }
];

export default function Home() {
  return <>
    <section className="hero">
      <div className="hero-copy"><span className="eyebrow">DUTCH FOOTBALL PERFORMANCE ACADEMY • ’T GOOI</span><h1>BUILD THE ATHLETE.<br/><span>IMPROVE THE PLAYER.</span></h1><p>FOOTWORK combineert voetbaltraining, kickboxing-inspired performance en fysieke ontwikkeling. Niet om van voetballers kickboksers te maken — wel om sterkere, snellere, explosievere en weerbaardere spelers te ontwikkelen.</p><div className="actions"><Link className="btn btn-orange" href="/contact">Plan een proeftraining →</Link><Link className="btn btn-outline" href="/footwork-8">Bekijk FOOTWORK 8</Link></div><div className="safe-note">✓ Geen hard sparren &nbsp; • &nbsp; ✓ Geen hoofdcontact &nbsp; • &nbsp; ✓ Jeugdgericht</div></div>
      <div className="hero-visual"><Image src="/images/hero-athletes.jpg" alt="FOOTWORK voetbal en performance training" fill priority sizes="(max-width: 900px) 100vw, 50vw"/><div className="hero-badge">MORE THAN<br/><em>FOOTBALL.</em></div></div>
    </section>
    <section className="pillarbar">{pillars.map(([icon,title,text])=><div className="pillar" key={title}><b>{icon}</b><span><strong>{title}</strong><small>{text}</small></span></div>)}</section>
    <section className="split section"><div className="photo tall"><Image src="/images/training-focus.jpg" alt="Jeugd performance training" fill sizes="(max-width: 800px) 100vw, 45vw"/></div><div className="section-copy"><span className="eyebrow">ONZE METHODE</span><h2>COMPLETE ATLETEN.<br/>BETERE VOETBALLERS.</h2><p>De moderne voetballer heeft meer nodig dan techniek alleen. Met onze F4 Performance Method trainen we coördinatie, kracht, snelheid en mentale scherpte als één geheel.</p><div className="method-grid"><article><span>F1</span><h3>FOOTWORK</h3><p>Coördinatie, agility, balans en richtingsveranderingen.</p></article><article><span>F2</span><h3>FORCE</h3><p>Core, kracht, stabiliteit en duelkracht.</p></article><article><span>F3</span><h3>FAST</h3><p>Acceleratie, explosiviteit en reactiesnelheid.</p></article><article><span>F4</span><h3>FOCUS</h3><p>Concentratie, discipline en mentale weerbaarheid.</p></article></div><Link className="text-link" href="/methode">Ontdek de volledige methode →</Link></div></section>
    <section className="section programs"><div className="section-heading"><span className="eyebrow">ONS AANBOD</span><h2>TRAIN. DEVELOP. PERFORM.</h2><p>Drie trainingsvormen, één doel: een completere voetballer.</p></div><div className="cards">{programs.map(p=><article className="card" key={p.title}><div className="card-img"><Image src={p.image} alt={p.title} fill sizes="(max-width:800px) 100vw, 33vw"/></div><div className="card-body"><h3>{p.title}</h3><p>{p.text}</p><Link href={p.href}>MEER INFO →</Link></div></article>)}</div></section>
    <section className="section home-fw8"><div className="fw8-number">8</div><div><span className="eyebrow">8 WEKEN • STARTTEST • EINDTEST</span><h2>FOOTWORK 8</h2><p>Ons complete ontwikkelprogramma waarin spelers acht weken gericht werken aan snelheid, kracht, coördinatie, explosiviteit, reactie en focus.</p><div className="home-stat-row"><div><strong>8</strong><span>weken</span></div><div><strong>6+</strong><span>metingen</span></div><div><strong>1</strong><span>Performance Card</span></div></div><Link className="btn btn-green" href="/footwork-8">Bekijk het 8-wekenprogramma →</Link></div></section>
    <section className="section audience"><div className="section-heading"><span className="eyebrow">VOOR WIE?</span><h2>ONTWIKKELEN OP HET JUISTE NIVEAU.</h2></div><div className="audience-grid"><article><span>8–10</span><h3>FOUNDATION</h3><p>Motoriek, coördinatie, plezier, houding en basisvoetwerk.</p></article><article><span>11–13</span><h3>DEVELOPMENT</h3><p>Snelheid, balans, techniek onder druk en gecontroleerde kracht.</p></article><article><span>14–16</span><h3>PERFORMANCE</h3><p>Explosiviteit, wedstrijdgerichte intensiteit, power en mentale scherpte.</p></article><article><span>ELITE</span><h3>SMALL GROUP</h3><p>Gerichte performancecoaching voor ambitieuze spelers in kleine groepen.</p></article></div></section>
    <section className="section club"><div className="club-copy"><span className="eyebrow">VOOR VOETBALCLUBS</span><h2>GEEN EXTRA TRAINING.<br/>EEN EXTRA DIMENSIE.</h2><p>FOOTWORK kan als aanvullend performanceblok binnen een jeugdopleiding worden ingezet. We sluiten aan op voetbal en maken fysieke progressie meetbaar.</p><Link className="btn btn-green" href="/voor-clubs">Bekijk clubprogramma's →</Link></div><div className="photo club-photo"><Image src="/images/football-performance.jpg" alt="Voetbal performance training" fill sizes="(max-width:800px) 100vw, 50vw"/></div></section>
    <section className="mini-cta"><span className="eyebrow">LOCATIE • ’T GOOI</span><h2>WORD DE BESTE VERSIE VAN JEZELF.</h2><p>Begin met een proeftraining of Performance Test en ontdek waar de grootste winst ligt.</p><div className="actions"><Link className="btn btn-orange" href="/contact">Proeftraining aanvragen →</Link><Link className="btn btn-outline" href="/performance-test">Performance Test bekijken</Link></div></section>
  </>;
}
